// resources/js/Pages/Reports/DeliveryStats.jsx
import { useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';
import {
    ArrowLeftIcon,
    TruckIcon,
    UsersIcon,
    CurrencyDollarIcon,
    CalendarIcon,
    ChartBarIcon
} from '@heroicons/react/24/outline';

export default function DeliveryStats({ auth, stats: initialStats, startDate, endDate }) {
    const formatDateForInput = (date) => {
        if (!date) return '';
        try {
            return new Date(date).toISOString().split('T')[0];
        } catch (error) {
            console.error('Error formatting date:', error);
            return '';
        }
    };

    const [searchStartDate, setSearchStartDate] = useState(formatDateForInput(startDate));
    const [searchEndDate, setSearchEndDate] = useState(formatDateForInput(endDate));
    const [isLoading, setIsLoading] = useState(false);
    const [filterErrors, setFilterErrors] = useState({});
    const [stats, setStats] = useState(initialStats);
    const [filteredStats, setFilteredStats] = useState(initialStats);

    const validateDateRange = (start, end) => {
        const errors = {};

        if (start && end) {
            const startDate = new Date(start);
            const endDate = new Date(end);

            if (startDate > endDate) {
                errors.dateRange = 'Start date cannot be after end date';
            }

            // Check if date range is too large (more than 1 year)
            const diffTime = Math.abs(endDate - startDate);
            const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
            if (diffDays > 365) {
                errors.dateRange = 'Date range cannot exceed 1 year for delivery stats';
            }
        }

        return errors;
    };

    const handleSearch = () => {
        try {
            setIsLoading(true);
            setFilterErrors({});

            // Validate date range
            const validationErrors = validateDateRange(searchStartDate, searchEndDate);
            if (Object.keys(validationErrors).length > 0) {
                setFilterErrors(validationErrors);
                setIsLoading(false);
                return;
            }

            // Build query parameters - only include non-empty values
            const params = new URLSearchParams();
            if (searchStartDate) params.append('start_date', searchStartDate);
            if (searchEndDate) params.append('end_date', searchEndDate);

            // Make AJAX request
            fetch(`/api/reports/delivery-stats-data?${params.toString()}`)
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        setFilteredStats(data.data);
                        setIsLoading(false);
                    } else {
                        setFilterErrors({ general: data.error || 'An error occurred' });
                        setIsLoading(false);
                    }
                })
                .catch(error => {
                    console.error('Error fetching data:', error);
                    setFilterErrors({ general: 'Network error occurred' });
                    setIsLoading(false);
                });
        } catch (error) {
            console.error('Error applying filter:', error);
            setFilterErrors({ general: 'An error occurred while applying the filter' });
            setIsLoading(false);
        }
    };

    const clearFilters = () => {
        setSearchStartDate('');
        setSearchEndDate('');
        setFilterErrors({});

        // Reset to initial data instead of fetching new data
        setFilteredStats(initialStats);
    };

    const formatCurrency = (amount) => {
        return `৳${parseFloat(amount || 0).toLocaleString()}`;
    };

    const totalDeliveries = filteredStats.reduce((sum, item) => sum + parseInt(item.total_deliveries || 0), 0);
    const totalAmount = filteredStats.reduce((sum, item) => sum + parseFloat(item.total_amount || 0), 0);
    const totalCommission = filteredStats.reduce((sum, item) => sum + parseFloat(item.total_commission || 0), 0);
    const averageCommissionRate = totalAmount > 0 ? (totalCommission / totalAmount) * 100 : 0;

    return (
        <AuthenticatedLayout
            user={auth.user}
            header={
                <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-4">
                        <Link
                            href="/reports"
                            className="inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                        >
                            <ArrowLeftIcon className="h-4 w-4 mr-2" />
                            Back to Reports
                        </Link>
                        <div>
                            <h2 className="font-semibold text-xl text-gray-800 leading-tight">
                                Delivery Statistics Report
                            </h2>
                            <p className="text-sm text-gray-600 mt-1">
                                Analyze delivery performance and commission rates
                            </p>
                        </div>
                    </div>
                    <div className="flex items-center space-x-2">
                        <TruckIcon className="h-8 w-8 text-gray-600" />
                    </div>
                </div>
            }
        >
            <Head title="Delivery Statistics Report" />

            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    {/* Date Filter */}
                    <div className="bg-white shadow rounded-lg p-6 mb-8">
                        <h3 className="text-lg font-medium text-gray-900 mb-4">Filter by Date Range</h3>

                        {/* Show general error */}
                        {filterErrors.general && (
                            <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-md">
                                <p className="text-red-800 text-sm">{filterErrors.general}</p>
                            </div>
                        )}

                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    Start Date <span className="text-gray-400">(optional)</span>
                                </label>
                                <input
                                    type="date"
                                    value={searchStartDate}
                                    onChange={(e) => setSearchStartDate(e.target.value)}
                                    className="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                    disabled={isLoading}
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    End Date <span className="text-gray-400">(optional)</span>
                                </label>
                                <input
                                    type="date"
                                    value={searchEndDate}
                                    onChange={(e) => setSearchEndDate(e.target.value)}
                                    className="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                                    disabled={isLoading}
                                />
                            </div>
                            <div className="flex items-end space-x-2">
                                <button
                                    onClick={handleSearch}
                                    disabled={isLoading}
                                    className="flex-1 inline-flex justify-center items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {isLoading ? (
                                        <>
                                            <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent mr-2"></div>
                                            Applying...
                                        </>
                                    ) : (
                                        <>
                                            <CalendarIcon className="h-4 w-4 mr-2" />
                                            Apply Filter
                                        </>
                                    )}
                                </button>
                                <button
                                    onClick={clearFilters}
                                    disabled={isLoading}
                                    className="inline-flex justify-center items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md shadow-sm text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    Clear
                                </button>
                            </div>
                        </div>

                        {/* Show date range error */}
                        {filterErrors.dateRange && (
                            <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-md">
                                <p className="text-red-800 text-sm">{filterErrors.dateRange}</p>
                            </div>
                        )}

                        {/* Active filter indicators */}
                        {(searchStartDate || searchEndDate) && (
                            <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-md">
                                <p className="text-blue-800 text-sm font-medium">Active Filters:</p>
                                <div className="mt-1 flex flex-wrap gap-2">
                                    {searchStartDate && (
                                        <span className="inline-flex items-center px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded-full">
                                            From: {searchStartDate}
                                        </span>
                                    )}
                                    {searchEndDate && (
                                        <span className="inline-flex items-center px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded-full">
                                            To: {searchEndDate}
                                        </span>
                                    )}
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Summary Cards */}
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
                        <div className="bg-white overflow-hidden shadow rounded-lg">
                            <div className="p-5">
                                <div className="flex items-center">
                                    <div className="flex-shrink-0">
                                        <UsersIcon className="h-8 w-8 text-blue-600" />
                                    </div>
                                    <div className="ml-5 w-0 flex-1">
                                        <dl>
                                            <dt className="text-sm font-medium text-gray-500 truncate">
                                                Active Employees
                                            </dt>
                                            <dd className="text-lg font-medium text-gray-900">
                                                {filteredStats.length}
                                            </dd>
                                        </dl>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="bg-white overflow-hidden shadow rounded-lg">
                            <div className="p-5">
                                <div className="flex items-center">
                                    <div className="flex-shrink-0">
                                        <TruckIcon className="h-8 w-8 text-green-600" />
                                    </div>
                                    <div className="ml-5 w-0 flex-1">
                                        <dl>
                                            <dt className="text-sm font-medium text-gray-500 truncate">
                                                Total Deliveries
                                            </dt>
                                            <dd className="text-lg font-medium text-gray-900">
                                                {totalDeliveries.toLocaleString()}
                                            </dd>
                                        </dl>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="bg-white overflow-hidden shadow rounded-lg">
                            <div className="p-5">
                                <div className="flex items-center">
                                    <div className="flex-shrink-0">
                                        <CurrencyDollarIcon className="h-8 w-8 text-indigo-600" />
                                    </div>
                                    <div className="ml-5 w-0 flex-1">
                                        <dl>
                                            <dt className="text-sm font-medium text-gray-500 truncate">
                                                Total Sales
                                            </dt>
                                            <dd className="text-lg font-medium text-gray-900">
                                                {formatCurrency(totalAmount)}
                                            </dd>
                                        </dl>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="bg-white overflow-hidden shadow rounded-lg">
                            <div className="p-5">
                                <div className="flex items-center">
                                    <div className="flex-shrink-0">
                                        <ChartBarIcon className="h-8 w-8 text-purple-600" />
                                    </div>
                                    <div className="ml-5 w-0 flex-1">
                                        <dl>
                                            <dt className="text-sm font-medium text-gray-500 truncate">
                                                Avg Commission Rate
                                            </dt>
                                            <dd className="text-lg font-medium text-gray-900">
                                                {averageCommissionRate.toFixed(2)}%
                                            </dd>
                                        </dl>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Delivery Statistics Table */}
                    <div className="bg-white shadow overflow-hidden sm:rounded-md">
                        <div className="px-4 py-5 sm:px-6">
                            <h3 className="text-lg leading-6 font-medium text-gray-900">
                                Employee Delivery Performance
                            </h3>
                            <p className="mt-1 max-w-2xl text-sm text-gray-500">
                                Detailed delivery statistics for each employee
                            </p>
                        </div>

                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-200">
                                <thead className="bg-gray-50">
                                    <tr>
                                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Employee Name
                                        </th>
                                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Total Deliveries
                                        </th>
                                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Total Amount
                                        </th>
                                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Total Commission
                                        </th>
                                        <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Commission Rate
                                        </th>
                                    </tr>
                                </thead>
                                <tbody className="bg-white divide-y divide-gray-200">
                                    {isLoading ? (
                                        <tr>
                                            <td colSpan="7" className="px-6 py-4 text-center text-gray-500">
                                                Loading...
                                            </td>
                                        </tr>
                                    ) : filteredStats.length === 0 ? (
                                        <tr>
                                            <td colSpan="7" className="px-6 py-4 text-center text-gray-500">
                                                No delivery stats found for the selected criteria
                                            </td>
                                        </tr>
                                    ) : (
                                        filteredStats.map((employee, index) => (
                                        <tr key={index} className="hover:bg-gray-50">
                                            <td className="px-6 py-4 whitespace-nowrap">
                                                <div className="flex items-center">
                                                    <div className="flex-shrink-0 h-10 w-10">
                                                        <div className="h-10 w-10 rounded-full bg-gray-300 flex items-center justify-center">
                                                            <span className="text-sm font-medium text-gray-700">
                                                                {employee.employee_name ? employee.employee_name.charAt(0).toUpperCase() : 'N'}
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div className="ml-4">
                                                        <div className="text-sm font-medium text-gray-900">
                                                            {employee.employee_name || 'N/A'}
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                                {parseInt(employee.total_deliveries || 0).toLocaleString()}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                                {formatCurrency(employee.total_amount)}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-green-600">
                                                {formatCurrency(employee.total_commission)}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap">
                                                <span className="inline-flex px-2 py-1 text-xs font-semibold rounded-full bg-blue-100 text-blue-800">
                                                    {parseFloat(employee.commission_rate || 0).toFixed(2)}%
                                                </span>
                                            </td>
                                        </tr>
                                    ))
                                    )}
                                </tbody>
                            </table>
                        </div>

                        {filteredStats.length === 0 && !isLoading && (
                            <div className="text-center py-12">
                                <TruckIcon className="mx-auto h-12 w-12 text-gray-400" />
                                <h3 className="mt-2 text-sm font-medium text-gray-900">No delivery data</h3>
                                <p className="mt-1 text-sm text-gray-500">
                                    No delivery statistics available for the selected date range.
                                </p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}

// resources/js/Pages/Reports/DeliveryStats.vue
<template>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class="flex justify-between items-center mb-6">
                        <h2 class="text-2xl font-semibold">Delivery Statistics Report</h2>
                        <Link :href="route('reports.index')" class="text-blue-500 hover:underline">
                            Back to Reports
                        </Link>
                    </div>

                    <div class="mb-6">
                        <form @submit.prevent="filterStats" class="flex gap-4">
                            <div>
                                <label class="block text-gray-700 text-sm font-bold mb-2" for="start_date">
                                    Start Date
                                </label>
                                <input
                                    v-model="form.start_date"
                                    type="date"
                                    id="start_date"
                                    class="shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                >
                            </div>
                            <div>
                                <label class="block text-gray-700 text-sm font-bold mb-2" for="end_date">
                                    End Date
                                </label>
                                <input
                                    v-model="form.end_date"
                                    type="date"
                                    id="end_date"
                                    class="shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                >
                            </div>
                            <div class="flex items-end">
                                <button
                                    type="submit"
                                    class="bg-blue-500 text-white px-4 py-2 rounded-md"
                                >
                                    Filter
                                </button>
                            </div>
                        </form>
                    </div>

                    <div class="overflow-x-auto">
                        <table class="min-w-full bg-white border">
                            <thead>
                                <tr>
                                    <th class="py-2 px-4 border-b">Employee Name</th>
                                    <th class="py-2 px-4 border-b">Total Deliveries</th>
                                    <th class="py-2 px-4 border-b">Total Amount</th>
                                    <th class="py-2 px-4 border-b">Average Per Delivery</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="stat in stats" :key="stat.employee_name">
                                    <td class="py-2 px-4 border-b">{{ stat.employee_name }}</td>
                                    <td class="py-2 px-4 border-b">{{ stat.total_deliveries }}</td>
                                    <td class="py-2 px-4 border-b">{{ formatCurrency(stat.total_amount) }}</td>
                                    <td class="py-2 px-4 border-b">{{ formatCurrency(stat.total_amount / stat.total_deliveries) }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="mt-6">
                        <h3 class="text-lg font-semibold mb-4">Summary</h3>
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div class="p-4 bg-gray-50 rounded-lg">
                                <p class="text-sm text-gray-600">Total Employees</p>
                                <p class="text-2xl font-bold">{{ stats.length }}</p>
                            </div>
                            <div class="p-4 bg-gray-50 rounded-lg">
                                <p class="text-sm text-gray-600">Total Deliveries</p>
                                <p class="text-2xl font-bold">{{ totalDeliveries }}</p>
                            </div>
                            <div class="p-4 bg-gray-50 rounded-lg">
                                <p class="text-sm text-gray-600">Total Amount</p>
                                <p class="text-2xl font-bold">{{ formatCurrency(totalAmount) }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { Link, useForm } from '@inertiajs/inertia-vue3';
import { computed } from 'vue';

const props = defineProps({
    stats: Array,
    startDate: String,
    endDate: String
});

const form = useForm({
    start_date: props.startDate,
    end_date: props.endDate
});

const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD'
    }).format(amount);
};

const totalDeliveries = computed(() => {
    return props.stats.reduce((sum, stat) => sum + stat.total_deliveries, 0);
});

const totalAmount = computed(() => {
    return props.stats.reduce((sum, stat) => sum + stat.total_amount, 0);
});

const filterStats = () => {
    form.get(route('reports.delivery-stats'), {
        preserveState: true
    });
};
</script>
