// resources/js/Pages/BalanceSheets/Show.vue
<template>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class="flex justify-between items-center mb-6">
                        <h2 class="text-2xl font-semibold">Balance Sheet Details</h2>
                        <div class="space-x-4">
                            <button @click="showUpdateBalanceModal = true" class="bg-blue-500 text-white px-4 py-2 rounded-md">
                                Update Balance
                            </button>
                        </div>
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                        <div class="bg-gray-50 p-4 rounded-lg">
                            <h3 class="text-lg font-semibold mb-2">Employee Details</h3>
                            <p><span class="font-medium">Name:</span> {{ balanceSheet.employee.name }}</p>
                            <p><span class="font-medium">Opening Balance:</span> {{ formatCurrency(balanceSheet.opening_balance) }}</p>
                            <p><span class="font-medium">Current Balance:</span> {{ formatCurrency(balanceSheet.current_balance) }}</p>
                        </div>
                    </div>

                    <h3 class="text-xl font-semibold mb-4">Product Deliveries</h3>
                    <div class="overflow-x-auto">
                        <table class="min-w-full bg-white border">
                            <thead>
                                <tr>
                                    <th class="py-2 px-4 border-b">Product</th>
                                    <th class="py-2 px-4 border-b">Quantity</th>
                                    <th class="py-2 px-4 border-b">Unit Price</th>
                                    <th class="py-2 px-4 border-b">Total Amount</th>
                                    <th class="py-2 px-4 border-b">Status</th>
                                    <th class="py-2 px-4 border-b">Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="delivery in deliveries.data" :key="delivery.id">
                                    <td class="py-2 px-4 border-b">{{ delivery.product.name }}</td>
                                    <td class="py-2 px-4 border-b">{{ delivery.quantity }}</td>
                                    <td class="py-2 px-4 border-b">{{ formatCurrency(delivery.unit_price) }}</td>
                                    <td class="py-2 px-4 border-b">{{ formatCurrency(delivery.total_amount) }}</td>
                                    <td class="py-2 px-4 border-b">{{ delivery.status }}</td>
                                    <td class="py-2 px-4 border-b">{{ formatDate(delivery.delivery_date) }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <Pagination :links="deliveries.links" class="mt-6" />

                    <!-- Update Balance Modal -->
                    <Modal :show="showUpdateBalanceModal" @close="showUpdateBalanceModal = false">
                        <div class="p-6">
                            <h3 class="text-lg font-medium text-gray-900 mb-4">Update Balance</h3>
                            <form @submit.prevent="updateBalance">
                                <div class="mb-4">
                                    <label class="block text-sm font-medium text-gray-700" for="type">
                                        Type
                                    </label>
                                    <select v-model="form.type" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">
                                        <option value="credit">Credit</option>
                                        <option value="debit">Debit</option>
                                    </select>
                                </div>

                                <div class="mb-4">
                                    <label class="block text-sm font-medium text-gray-700" for="amount">
                                        Amount
                                    </label>
                                    <input
                                        v-model="form.amount"
                                        type="number"
                                        step="0.01"
                                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"
                                        required
                                    >
                                </div>

                                <div class="flex justify-end space-x-3">
                                    <button
                                        type="button"
                                        @click="showUpdateBalanceModal = false"
                                        class="bg-gray-300 text-gray-700 px-4 py-2 rounded-md"
                                    >
                                        Cancel
                                    </button>
                                    <button
                                        type="submit"
                                        class="bg-blue-500 text-white px-4 py-2 rounded-md"
                                        :disabled="form.processing"
                                    >
                                        Update
                                    </button>
                                </div>
                            </form>
                        </div>
                    </Modal>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import { Link, useForm } from '@inertiajs/inertia-vue3';
import Pagination from '@/Components/Pagination.vue';
import Modal from '@/Components/Modal.vue';

const props = defineProps({
    balanceSheet: Object,
    deliveries: Object
});

const showUpdateBalanceModal = ref(false);

const form = useForm({
    type: 'credit',
    amount: ''
});

const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD'
    }).format(amount);
};

const formatDate = (date) => {
    return new Date(date).toLocaleDateString();
};

const updateBalance = () => {
    form.post(route('balance-sheets.update-balance', props.balanceSheet.employee_id), {
        onSuccess: () => {
            showUpdateBalanceModal.value = false;
            form.reset();
        }
    });
};
</script>

// resources/js/Pages/Positions/Show.jsx
import React from 'react';
import { Head, Link, router } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { showToast } from '@/utils/toast.jsx';
import {
    ArrowLeftIcon,
    PencilSquareIcon,
    TrashIcon,
    UsersIcon,
    CurrencyDollarIcon,
    CheckIcon,
    XMarkIcon
} from '@heroicons/react/24/outline';

export default function Show({ position }) {
    const handleDelete = () => {
        showToast.confirmDelete(`position "${position.name}"`, () => {
            const loadingToast = showToast.loading('Deleting position...');
            router.delete(route('positions.destroy', { position: position.id }), {
                onFinish: () => {
                    showToast.dismiss(loadingToast);
                }
            });
        });
    };

    const formatCurrency = (amount) => {
        return new Intl.NumberFormat('en-US', {
            style: 'currency',
            currency: 'USD'
        }).format(amount || 0);
    };

    return (
        <AuthenticatedLayout
            header={
                <div className="flex justify-between items-center">
                    <div className="flex items-center gap-4">
                        <Link
                            href={route('positions.index')}
                            className="text-gray-600 hover:text-gray-900"
                        >
                            <ArrowLeftIcon className="w-5 h-5" />
                        </Link>
                        <div>
                            <h2 className="font-semibold text-xl text-gray-800 leading-tight">
                                {position.name}
                            </h2>
                            <p className="text-sm text-gray-600">Position Details</p>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <Link
                            href={route('positions.edit', { position: position.id })}
                            className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
                        >
                            <PencilSquareIcon className="w-4 h-4" />
                            Edit
                        </Link>
                        <button
                            onClick={handleDelete}
                            className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors"
                        >
                            <TrashIcon className="w-4 h-4" />
                            Delete
                        </button>
                    </div>
                </div>
            }
        >
            <Head title={`Position: ${position.name}`} />

            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        {/* Position Details */}
                        <div className="lg:col-span-2">
                            <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                                <div className="p-6">
                                    <h3 className="text-lg font-semibold text-gray-900 mb-4">Position Information</h3>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700">Position Name</label>
                                            <p className="mt-1 text-sm text-gray-900">{position.name}</p>
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700">Status</label>
                                            <div className="mt-1">
                                                <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                                                    position.is_active
                                                        ? 'bg-green-100 text-green-800'
                                                        : 'bg-red-100 text-red-800'
                                                }`}>
                                                    {position.is_active ? (
                                                        <>
                                                            <CheckIcon className="w-3 h-3 mr-1" />
                                                            Active
                                                        </>
                                                    ) : (
                                                        <>
                                                            <XMarkIcon className="w-3 h-3 mr-1" />
                                                            Inactive
                                                        </>
                                                    )}
                                                </span>
                                            </div>
                                        </div>

                                        <div className="md:col-span-2">
                                            <label className="block text-sm font-medium text-gray-700">Description</label>
                                            <p className="mt-1 text-sm text-gray-900">
                                                {position.description || 'No description provided.'}
                                            </p>
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700">Minimum Salary</label>
                                            <p className="mt-1 text-sm text-gray-900">
                                                {position.salary_range_min ? formatCurrency(position.salary_range_min) : 'Not specified'}
                                            </p>
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700">Maximum Salary</label>
                                            <p className="mt-1 text-sm text-gray-900">
                                                {position.salary_range_max ? formatCurrency(position.salary_range_max) : 'Not specified'}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Statistics */}
                        <div className="space-y-6">
                            <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                                <div className="p-6">
                                    <div className="flex items-center">
                                        <div className="flex-shrink-0">
                                            <UsersIcon className="h-8 w-8 text-blue-600" />
                                        </div>
                                        <div className="ml-4">
                                            <div className="text-sm font-medium text-gray-500">Total Employees</div>
                                            <div className="text-2xl font-bold text-gray-900">
                                                {position.users?.length || 0}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {position.salary_range_min && position.salary_range_max && (
                                <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                                    <div className="p-6">
                                        <div className="flex items-center">
                                            <div className="flex-shrink-0">
                                                <CurrencyDollarIcon className="h-8 w-8 text-green-600" />
                                            </div>
                                            <div className="ml-4">
                                                <div className="text-sm font-medium text-gray-500">Salary Range</div>
                                                <div className="text-lg font-semibold text-gray-900">
                                                    {formatCurrency(position.salary_range_min)} - {formatCurrency(position.salary_range_max)}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Employees in this Position */}
                    {position.users && position.users.length > 0 && (
                        <div className="mt-8">
                            <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                                <div className="p-6">
                                    <h3 className="text-lg font-semibold text-gray-900 mb-4">
                                        Employees in this Position ({position.users.length})
                                    </h3>

                                    <div className="overflow-x-auto">
                                        <table className="min-w-full divide-y divide-gray-200">
                                            <thead className="bg-gray-50">
                                                <tr>
                                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                        Employee
                                                    </th>
                                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                        Employee ID
                                                    </th>
                                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                        Email
                                                    </th>
                                                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                        Current Salary
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody className="bg-white divide-y divide-gray-200">
                                                {position.users.map((user) => (
                                                    <tr key={user.id} className="hover:bg-gray-50">
                                                        <td className="px-6 py-4 whitespace-nowrap">
                                                            <div className="font-medium text-gray-900">{user.name}</div>
                                                        </td>
                                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                            {user.employee_id || 'N/A'}
                                                        </td>
                                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                            {user.email}
                                                        </td>
                                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                            {user.current_salary ? formatCurrency(user.current_salary) : 'Not set'}
                                                        </td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
