// resources/js/Components/StockAdjustmentModal.jsx
import { useForm } from '@inertiajs/react';
import { Fragment } from 'react';
import { Dialog, Transition } from '@headlessui/react';
import { XMarkIcon, MinusIcon, PlusIcon } from '@heroicons/react/24/outline';

export default function StockAdjustmentModal({ show, product, onClose }) {
    const { data, setData, post, processing, reset } = useForm({
        adjustment: 0,
        reason: ''
    });

    const submit = (e) => {
        e.preventDefault();
        post(route('products.update-stock', product.id), {
            preserveScroll: true,
            onSuccess: () => {
                reset();
                onClose();
            }
        });
    };

    const handleClose = () => {
        reset();
        onClose();
    };

    const incrementAdjustment = () => {
        setData('adjustment', parseInt(data.adjustment || 0) + 1);
    };

    const decrementAdjustment = () => {
        setData('adjustment', parseInt(data.adjustment || 0) - 1);
    };

    if (!product) return null;

    return (
        <Transition appear show={show} as={Fragment}>
            <Dialog as="div" className="relative z-50" onClose={handleClose}>
                <Transition.Child
                    as={Fragment}
                    enter="ease-out duration-300"
                    enterFrom="opacity-0"
                    enterTo="opacity-100"
                    leave="ease-in duration-200"
                    leaveFrom="opacity-100"
                    leaveTo="opacity-0"
                >
                    <div className="fixed inset-0 bg-black bg-opacity-25" />
                </Transition.Child>

                <div className="fixed inset-0 overflow-y-auto">
                    <div className="flex min-h-full items-center justify-center p-4 text-center">
                        <Transition.Child
                            as={Fragment}
                            enter="ease-out duration-300"
                            enterFrom="opacity-0 scale-95"
                            enterTo="opacity-100 scale-100"
                            leave="ease-in duration-200"
                            leaveFrom="opacity-100 scale-100"
                            leaveTo="opacity-0 scale-95"
                        >
                            <Dialog.Panel className="w-full max-w-md transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all">
                                <Dialog.Title
                                    as="h3"
                                    className="text-lg font-medium leading-6 text-gray-900 flex justify-between items-center"
                                >
                                    Stock Adjustment - {product.name}
                                    <button
                                        type="button"
                                        className="text-gray-400 hover:text-gray-600"
                                        onClick={handleClose}
                                    >
                                        <XMarkIcon className="h-6 w-6" />
                                    </button>
                                </Dialog.Title>

                                <form onSubmit={submit} className="mt-4">
                                    <div className="mb-4">
                                        <label className="block text-sm font-medium text-gray-700 mb-2">
                                            Stock Adjustment
                                        </label>
                                        <div className="flex items-center">
                                            <button
                                                type="button"
                                                className="bg-red-500 text-white p-2 rounded-l hover:bg-red-600"
                                                onClick={decrementAdjustment}
                                            >
                                                <MinusIcon className="h-4 w-4" />
                                            </button>
                                            <input
                                                type="number"
                                                value={data.adjustment}
                                                onChange={(e) => setData('adjustment', e.target.value)}
                                                className="border-t border-b text-center w-20 py-2 focus:outline-none"
                                                required
                                            />
                                            <button
                                                type="button"
                                                className="bg-green-500 text-white p-2 rounded-r hover:bg-green-600"
                                                onClick={incrementAdjustment}
                                            >
                                                <PlusIcon className="h-4 w-4" />
                                            </button>
                                        </div>
                                    </div>

                                    <div className="mb-4">
                                        <label className="block text-sm font-medium text-gray-700 mb-2">
                                            Reason
                                        </label>
                                        <input
                                            type="text"
                                            value={data.reason}
                                            onChange={(e) => setData('reason', e.target.value)}
                                            className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                                            required
                                            placeholder="Enter reason for stock adjustment"
                                        />
                                    </div>

                                    <div className="mb-6 text-sm text-gray-600 bg-gray-50 p-3 rounded">
                                        <p>Current Stock: <span className="font-semibold">{product.stock_quantity}</span></p>
                                        <p>New Stock: <span className="font-semibold">{product.stock_quantity + (parseInt(data.adjustment) || 0)}</span></p>
                                    </div>

                                    <div className="flex justify-end space-x-3">
                                        <button
                                            type="button"
                                            className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                                            onClick={handleClose}
                                        >
                                            Cancel
                                        </button>
                                        <button
                                            type="submit"
                                            disabled={processing}
                                            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
                                        >
                                            {processing ? 'Updating...' : 'Update Stock'}
                                        </button>
                                    </div>
                                </form>
                            </Dialog.Panel>
                        </Transition.Child>
                    </div>
                </div>
            </Dialog>
        </Transition>
    );
}

// resources/js/Components/StockAdjustmentModal.vue
<template>
    <div class="fixed inset-0 overflow-y-auto" v-if="show">
        <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
            <div class="fixed inset-0 transition-opacity" @click="close">
                <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
            </div>

            <span class="hidden sm:inline-block sm:align-middle sm:h-screen"></span>&#8203;

            <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
                <form @submit.prevent="submit">
                    <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                        <div class="mb-4">
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="adjustment">
                                Stock Adjustment
                            </label>
                            <div class="flex items-center">
                                <button
                                    type="button"
                                    class="bg-red-500 text-white px-3 py-2 rounded-l"
                                    @click="() => form.adjustment = parseInt(form.adjustment || 0) - 1"
                                >
                                    -
                                </button>
                                <input
                                    v-model="form.adjustment"
                                    type="number"
                                    class="shadow appearance-none border text-center w-20 py-2"
                                    required
                                >
                                <button
                                    type="button"
                                    class="bg-green-500 text-white px-3 py-2 rounded-r"
                                    @click="() => form.adjustment = parseInt(form.adjustment || 0) + 1"
                                >
                                    +
                                </button>
                            </div>
                        </div>

                        <div class="mb-4">
                            <label class="block text-gray-700 text-sm font-bold mb-2" for="reason">
                                Reason
                            </label>
                            <input
                                v-model="form.reason"
                                class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                type="text"
                                required
                            >
                        </div>

                        <div class="text-sm text-gray-500">
                            <p>Current Stock: {{ product.stock_quantity }}</p>
                            <p>New Stock: {{ product.stock_quantity + (parseInt(form.adjustment) || 0) }}</p>
                        </div>
                    </div>

                    <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                        <button
                            type="submit"
                            class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-blue-600 text-base font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 sm:ml-3 sm:w-auto sm:text-sm"
                            :disabled="form.processing"
                        >
                            Update Stock
                        </button>
                        <button
                            type="button"
                            class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
                            @click="close"
                        >
                            Cancel
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</template>

<script setup>
import { useForm } from '@inertiajs/inertia-vue3';

const props = defineProps({
    show: Boolean,
    product: Object
});

const emit = defineEmits(['close']);

const form = useForm({
    adjustment: 0,
    reason: ''
});

const submit = () => {
    form.post(route('products.update-stock', props.product.id), {
        preserveScroll: true,
        onSuccess: () => {
            form.reset();
            emit('close');
        }
    });
};

const close = () => {
    form.reset();
    emit('close');
};
</script>
