// resources/js/Layouts/AuthenticatedLayout.vue
<template>
    <div>
        <div class="min-h-screen bg-gray-100">
            <nav class="bg-white border-b border-gray-100">
                <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div class="flex justify-between h-16">
                        <div class="flex">
                            <!-- Logo -->
                            <div class="shrink-0 flex items-center">
                                <Link :href="route('dashboard')">
                                    <img v-if="$page.props.settings?.app_logo" :src="$page.props.settings.app_logo" class="h-9 w-auto" :alt="$page.props.settings?.app_name" />
                                    <ApplicationLogo v-else class="block h-9 w-auto fill-current text-gray-800" />
                                </Link>
                                <span v-if="$page.props.settings?.app_name" class="ml-3 text-xl font-semibold">{{ $page.props.settings.app_name }}</span>
                            </div>

                            <!-- Navigation Links -->
                            <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                                <NavLink :href="route('dashboard')" :active="route().current('dashboard')">
                                    Dashboard
                                </NavLink>
                                <NavLink :href="route('employees.index')" :active="route().current('employees.*')">
                                    Employees
                                </NavLink>
                                <NavLink :href="route('products.index')" :active="route().current('products.*')">
                                    Products
                                </NavLink>
                                <NavLink :href="route('product-deliveries.index')" :active="route().current('product-deliveries.*')">
                                    Deliveries
                                </NavLink>
                                <NavLink :href="route('balance-sheets.index')" :active="route().current('balance-sheets.*')">
                                    Balance Sheets
                                </NavLink>
                                <NavLink v-if="$page.props.auth.user.roles.includes('admin')"
                                    :href="route('roles.index')"
                                    :active="route().current('roles.*')">
                                    Roles
                                </NavLink>
                                <NavLink v-if="$page.props.auth.user.roles.includes('admin')"
                                    :href="route('permissions.index')"
                                    :active="route().current('permissions.*')">
                                    Permissions
                                </NavLink>
                                <NavLink v-if="['admin', 'manager'].some(role => $page.props.auth.user.roles.includes(role))"
                                    :href="route('reports.index')"
                                    :active="route().current('reports.*')">
                                    Reports
                                </NavLink>
                            </div>
                        </div>

                        <div class="hidden sm:flex sm:items-center sm:ml-6">
                            <div class="ml-3 relative">
                                <Dropdown align="right" width="48">
                                    <template #trigger>
                                        <span class="inline-flex rounded-md">
                                            <button
                                                type="button"
                                                class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150"
                                            >
                                                {{ $page.props.auth.user.name }}

                                                <svg
                                                    class="ml-2 -mr-0.5 h-4 w-4"
                                                    xmlns="http://www.w3.org/2000/svg"
                                                    viewBox="0 0 20 20"
                                                    fill="currentColor"
                                                >
                                                    <path
                                                        fill-rule="evenodd"
                                                        d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                                        clip-rule="evenodd"
                                                    />
                                                </svg>
                                            </button>
                                        </span>
                                    </template>

                                    <template #content>
                                        <DropdownLink :href="route('profile.edit')">
                                            Profile
                                        </DropdownLink>
                                        <DropdownLink :href="route('logout')" method="post" as="button">
                                            Log Out
                                        </DropdownLink>
                                    </template>
                                </Dropdown>
                            </div>
                        </div>

                        <!-- Hamburger -->
                        <div class="-mr-2 flex items-center sm:hidden">
                            <button
                                @click="showingNavigationDropdown = !showingNavigationDropdown"
                                class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out"
                            >
                                <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                                    <path
                                        :class="{
                                            hidden: showingNavigationDropdown,
                                            'inline-flex': !showingNavigationDropdown,
                                        }"
                                        stroke-linecap="round"
                                        stroke-linejoin="round"
                                        stroke-width="2"
                                        d="M4 6h16M4 12h16M4 18h16"
                                    />
                                    <path
                                        :class="{
                                            hidden: !showingNavigationDropdown,
                                            'inline-flex': showingNavigationDropdown,
                                        }"
                                        stroke-linecap="round"
                                        stroke-linejoin="round"
                                        stroke-width="2"
                                        d="M6 18L18 6M6 6l12 12"
                                    />
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Responsive Navigation Menu -->
                <div
                    :class="{
                        block: showingNavigationDropdown,
                        hidden: !showingNavigationDropdown,
                    }"
                    class="sm:hidden"
                >
                    <div class="pt-2 pb-3 space-y-1">
                        <ResponsiveNavLink :href="route('dashboard')" :active="route().current('dashboard')">
                            Dashboard
                        </ResponsiveNavLink>
                        <ResponsiveNavLink :href="route('employees.index')" :active="route().current('employees.*')">
                            Employees
                        </ResponsiveNavLink>
                        <ResponsiveNavLink :href="route('products.index')" :active="route().current('products.*')">
                            Products
                        </ResponsiveNavLink>
                        <ResponsiveNavLink :href="route('product-deliveries.index')" :active="route().current('product-deliveries.*')">
                            Deliveries
                        </ResponsiveNavLink>
                        <ResponsiveNavLink :href="route('balance-sheets.index')" :active="route().current('balance-sheets.*')">
                            Balance Sheets
                        </ResponsiveNavLink>
                        <ResponsiveNavLink v-if="$page.props.auth.user.roles.includes('admin')"
                            :href="route('roles.index')"
                            :active="route().current('roles.*')">
                            Roles
                        </ResponsiveNavLink>
                        <ResponsiveNavLink v-if="$page.props.auth.user.roles.includes('admin')"
                            :href="route('permissions.index')"
                            :active="route().current('permissions.*')">
                            Permissions
                        </ResponsiveNavLink>
                        <ResponsiveNavLink v-if="['admin', 'manager'].some(role => $page.props.auth.user.roles.includes(role))"
                            :href="route('reports.index')"
                            :active="route().current('reports.*')">
                            Reports
                        </ResponsiveNavLink>
                    </div>

                    <!-- Responsive Settings Options -->
                    <div class="pt-4 pb-1 border-t border-gray-200">
                        <div class="px-4">
                            <div class="font-medium text-base text-gray-800">
                                {{ $page.props.auth.user.name }}
                            </div>
                            <div class="font-medium text-sm text-gray-500">{{ $page.props.auth.user.email }}</div>
                        </div>

                        <div class="mt-3 space-y-1">
                            <ResponsiveNavLink :href="route('profile.edit')">Profile</ResponsiveNavLink>
                            <ResponsiveNavLink :href="route('logout')" method="post" as="button">
                                Log Out
                            </ResponsiveNavLink>
                        </div>
                    </div>
                </div>
            </nav>

            <!-- Page Heading -->
            <header class="bg-white shadow" v-if="$slots.header">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    <slot name="header" />
                </div>
            </header>

            <!-- Page Content -->
            <main>
                <slot />
            </main>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import ApplicationLogo from '@/Components/ApplicationLogo.vue';
import Dropdown from '@/Components/Dropdown.vue';
import DropdownLink from '@/Components/DropdownLink.vue';
import NavLink from '@/Components/NavLink.vue';
import ResponsiveNavLink from '@/Components/ResponsiveNavLink.vue';
import { Link } from '@inertiajs/inertia-vue3';

const showingNavigationDropdown = ref(false);
</script>

// resources/js/Layouts/AuthenticatedLayout.jsx
import { useState } from 'react';
import ApplicationLogo from '@/Components/ApplicationLogo';
import Dropdown from '@/Components/Dropdown';
import NavLink from '@/Components/NavLink';
import ResponsiveNavLink from '@/Components/ResponsiveNavLink';
import { Link, usePage } from '@inertiajs/react';
import {
    HomeIcon,
    UserGroupIcon,
    CurrencyDollarIcon,
    TruckIcon,
    DocumentTextIcon,
    ChartBarIcon,
    CogIcon,
    Bars3Icon,
    XMarkIcon,
    ShieldCheckIcon,
    BuildingOfficeIcon,
    CalendarIcon,
    ClipboardDocumentListIcon,
    BanknotesIcon,
    ArrowTrendingUpIcon,
    DocumentArrowUpIcon,
    UsersIcon,
    KeyIcon
} from '@heroicons/react/24/outline';

export default function AuthenticatedLayout({ user, header, children }) {
    const [showingNavigationDropdown, setShowingNavigationDropdown] = useState(false);
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
    const { url } = usePage();

    // Helper function to check if user is super admin
    const isSuperAdmin = () => {
        return user?.is_super_admin === true;
    };

    // Helper function to check if route is current
    const isCurrentRoute = (routeName) => {
        const currentPath = url;

        if (routeName === 'dashboard') {
            return currentPath === '/dashboard';
        }

        if (routeName === 'employees.*') {
            return currentPath.startsWith('/employees');
        }

        if (routeName === 'products.*') {
            return currentPath.startsWith('/products');
        }

        if (routeName === 'product-deliveries.*') {
            return currentPath.startsWith('/product-deliveries');
        }

        if (routeName === 'balance-sheets.*') {
            return currentPath.startsWith('/balance-sheets');
        }

        if (routeName === 'expenses.*') {
            return currentPath.startsWith('/expenses');
        }

        if (routeName === 'reports.*') {
            return currentPath.startsWith('/reports');
        }

        if (routeName === 'admin.*') {
            return currentPath.startsWith('/admin');
        }

        if (routeName === 'roles.*') {
            return currentPath.startsWith('/roles');
        }

        if (routeName === 'permissions.*') {
            return currentPath.startsWith('/permissions');
        }

        if (routeName === 'settings.*') {
            return currentPath.startsWith('/settings');
        }

        return false;
    };

    // Define navigation sections with permissions
    // Define navigation sections
    const navigationSections = [
        {
            title: 'Dashboard',
            items: [
                {
                    name: 'Dashboard',
                    href: route('dashboard'),
                    icon: HomeIcon,
                    current: isCurrentRoute('dashboard')
                },
            ]
        },
        {
            title: 'Employee Management',
            items: [
                {
                    name: 'Employees',
                    href: route('employees.index'),
                    icon: UserGroupIcon,
                    current: isCurrentRoute('employees.*')
                },
            ]
        },
        {
            title: 'Operations',
            items: [
                {
                    name: 'Products',
                    href: route('products.index'),
                    icon: TruckIcon,
                    current: isCurrentRoute('products.*')
                },
                {
                    name: 'Product Deliveries',
                    href: route('product-deliveries.index'),
                    icon: DocumentTextIcon,
                    current: isCurrentRoute('product-deliveries.*')
                },
                {
                    name: 'Balance Sheets',
                    href: route('balance-sheets.index'),
                    icon: BanknotesIcon,
                    current: isCurrentRoute('balance-sheets.*')
                },
                {
                    name: 'Expenses',
                    href: route('expenses.index'),
                    icon: CurrencyDollarIcon,
                    current: isCurrentRoute('expenses.*')
                },
            ]
        },
        {
            title: 'Reports & Analytics',
            items: [
                {
                    name: 'Reports',
                    href: route('reports.index'),
                    icon: ChartBarIcon,
                    current: isCurrentRoute('reports.*')
                },
            ]
        },
        // Admin section - only for super admin
        ...(isSuperAdmin() ? [{
            title: 'Administration',
            items: [
                {
                    name: 'User Management',
                    href: route('admin.user-permissions'),
                    icon: UsersIcon,
                    current: isCurrentRoute('admin.*')
                },
                {
                    name: 'Roles',
                    href: route('roles.index'),
                    icon: ShieldCheckIcon,
                    current: isCurrentRoute('roles.*')
                },
                {
                    name: 'Permissions',
                    href: route('permissions.index'),
                    icon: KeyIcon,
                    current: isCurrentRoute('permissions.*')
                },
                {
                    name: 'Settings',
                    href: route('settings.index'),
                    icon: CogIcon,
                    current: isCurrentRoute('settings.*')
                },
            ]
        }] : [])
    ];

    // No filtering needed - just use the sections as-is
    const filteredNavigation = navigationSections;

    return (
        <div className="h-screen bg-gray-50 flex overflow-hidden">
            {/* Sidebar */}
            <div className={`${sidebarCollapsed ? 'w-16' : 'w-64'} fixed inset-y-0 left-0 z-50 bg-gradient-to-b from-gray-900 to-gray-800 transform ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} transition-all duration-300 ease-in-out lg:translate-x-0 lg:static lg:inset-0 shadow-xl flex flex-col`}>
                <div className="flex items-center justify-center h-16 bg-gray-900 border-b border-gray-700 flex-shrink-0">
                    {!sidebarCollapsed ? (
                        <>
                            <ApplicationLogo className="block h-9 w-auto fill-current text-blue-400" />
                            <span className="ml-2 text-white font-bold text-xl tracking-wide">EMS</span>
                        </>
                    ) : (
                        <ApplicationLogo className="block h-8 w-auto fill-current text-blue-400" />
                    )}
                </div>

                <nav className="flex-1 mt-5 px-2 overflow-y-auto scrollbar-thin scrollbar-thumb-gray-600 scrollbar-track-gray-800">
                    {filteredNavigation.map((section, sectionIndex) => (
                        <div key={section.title} className={sectionIndex > 0 ? 'mt-8' : ''}>
                            {!sidebarCollapsed && (
                                <h3 className="px-3 text-xs font-semibold text-gray-400 uppercase tracking-wider">
                                    {section.title}
                                </h3>
                            )}
                            <div className={`${!sidebarCollapsed ? 'mt-2' : ''} space-y-1`}>
                                {section.items.map((item) => (
                                    <div key={item.name} className="relative group">
                                        <Link
                                            href={item.href}
                                            className={`${
                                                item.current
                                                    ? 'bg-gradient-to-r from-blue-600 to-blue-500 text-white shadow-lg'
                                                    : 'text-gray-300 hover:bg-gray-700 hover:text-white'
                                            } group flex items-center ${sidebarCollapsed ? 'justify-center' : 'px-3'} py-2 text-sm font-medium rounded-lg transition-all duration-200 ease-in-out ${!sidebarCollapsed && 'transform hover:scale-105'}`}
                                        >
                                            <item.icon
                                                className={`${
                                                    item.current
                                                        ? 'text-white'
                                                        : 'text-gray-400 group-hover:text-white'
                                                } ${sidebarCollapsed ? 'h-6 w-6' : 'mr-3 h-5 w-5'}`}
                                            />
                                            {!sidebarCollapsed && item.name}
                                        </Link>
                                        {sidebarCollapsed && (
                                            <div className="absolute left-full ml-2 top-0 bg-gray-800 text-white px-2 py-1 rounded text-sm opacity-0 group-hover:opacity-100 transition-opacity duration-200 whitespace-nowrap z-50">
                                                {item.name}
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    ))}
                </nav>

                {/* User info at bottom */}
                <div className="flex-shrink-0 p-4 bg-gray-800 border-t border-gray-700">
                    <div className={`flex items-center ${sidebarCollapsed ? 'justify-center' : ''}`}>
                        <div className="flex-shrink-0">
                            <div className="h-8 w-8 rounded-full bg-blue-500 flex items-center justify-center">
                                <span className="text-sm font-medium text-white">
                                    {user?.name?.charAt(0).toUpperCase()}
                                </span>
                            </div>
                        </div>
                        {!sidebarCollapsed && (
                            <div className="ml-3 min-w-0 flex-1">
                                <p className="text-sm font-medium text-white truncate">{user?.name}</p>
                                <p className="text-xs text-gray-400 truncate">
                                    {user?.roles?.[0]?.name?.replace('-', ' ').toUpperCase() || 'Employee'}
                                </p>
                            </div>
                        )}
                    </div>
                </div>

                {/* Sidebar Toggle Button */}
                <button
                    onClick={() => setSidebarCollapsed(!sidebarCollapsed)}
                    className="hidden lg:flex absolute -right-3 top-20 bg-blue-600 hover:bg-blue-700 text-white rounded-full p-1.5 shadow-lg transition-colors duration-200 z-10"
                >
                    {sidebarCollapsed ? (
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                        </svg>
                    ) : (
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                        </svg>
                    )}
                </button>
            </div>

            {/* Mobile sidebar overlay */}
            {sidebarOpen && (
                <div className="fixed inset-0 z-40 lg:hidden">
                    <div className="fixed inset-0 bg-gray-600 bg-opacity-75" onClick={() => setSidebarOpen(false)}></div>
                </div>
            )}

            {/* Main content */}
            <div className="flex-1 flex flex-col min-w-0 h-screen">
                {/* Top navigation */}
                <div className="flex-shrink-0 flex h-16 bg-white shadow-sm border-b border-gray-200">
                    <button
                        type="button"
                        className="px-4 border-r border-gray-200 text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500 lg:hidden"
                        onClick={() => setSidebarOpen(true)}
                    >
                        <span className="sr-only">Open sidebar</span>
                        <Bars3Icon className="h-6 w-6" aria-hidden="true" />
                    </button>

                    <div className="flex-1 px-4 flex justify-between items-center min-w-0">
                        <div className="flex-1 min-w-0">
                            {header && (
                                <header className="py-2">
                                    <div className="text-lg font-semibold text-gray-900 truncate">{header}</div>
                                </header>
                            )}
                        </div>

                        <div className="ml-4 flex items-center md:ml-6">
                            {/* User dropdown */}
                            <Dropdown>
                                <Dropdown.Trigger>
                                    <span className="inline-flex rounded-md">
                                        <button
                                            type="button"
                                            className="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150"
                                        >
                                            {user?.name}
                                            <svg
                                                className="ml-2 -mr-0.5 h-4 w-4"
                                                xmlns="http://www.w3.org/2000/svg"
                                                viewBox="0 0 20 20"
                                                fill="currentColor"
                                            >
                                                <path
                                                    fillRule="evenodd"
                                                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                                    clipRule="evenodd"
                                                />
                                            </svg>
                                        </button>
                                    </span>
                                </Dropdown.Trigger>

                                <Dropdown.Content>
                                    <Dropdown.Link href={route('profile.edit')}>Profile</Dropdown.Link>
                                    <Dropdown.Link href={route('logout')} method="post" as="button">
                                        Log Out
                                    </Dropdown.Link>
                                </Dropdown.Content>
                            </Dropdown>
                        </div>
                    </div>
                </div>

                {/* Page content */}
                <main className="flex-1 overflow-y-auto bg-gray-50 hide-scrollbar">
                    <div className="py-6">
                        {children}
                    </div>
                </main>
            </div>
        </div>
    );
}
